"""
GIVEN THE PARTICIPANTS' SCORE SHEET FOR YOUR UNIVERSITY SPORT DAY, YOU ARE REQUIRED TO FIND THE RUNNER UP SCORE.
YOU ARE GIVEN N SCORES. STORE THEM IN A LIST AND FIND THE SCORE OF THE RUNNER UP.
INPUT FORMAT:
THE FIRST LINE CONTAINS N. THE SECOND LINE CONTAINS AN ARRAY A[] OF N INTEGERS EACH SEPARATED BY A SPACE.
CONSTRAINTS:
2<=N<=10
-100<=A[I]<=100
OUTPUT FORMAT:
PRINT THE RUNNER UP SCORE.
SAMPLE INPUT:
5
2 3 6 6 5
SAMPLE OUTPUT:
5
EXPLANATION:
GIVEN LIST IS [2, 3, 6, 6, 5]. THE MAXIMUM SCORE IS 6, SECOND MAXIMUM IS 5. HENCE, WE PRINT 5 AS THE RUNNER UP SCORE.
"""

if __name__=='__main__':
    N = int(input())
    ARR = map(int, input().split())
    print(sorted(list(set(ARR)))[-2])