"""
MR. ANANT ASANKHYA IS THE MANAGER AT THE INFINITE HOTEL. THE HOTEL HAS AN INFINITE AMOUNT OF ROOMS.
ONE FINE DAY, A FINITE NUMBER OF TOURISTS COME TO STAY AT THE HOTEL.
THE TOURISTS CONSISTS OF:
-A CAPTAIN.
-AN UNKNOWN GROUP OF FAMILIES CONSISTING OF K MEMBERS PER GROUP WHERE K != 1.
THE CAPTAIN WAS GIVEN A SEPARATE ROOM, AND THE REST WERE GIVEN ONE ROOM PER GROUP.
MR. ANANT HAS AN UNORDEREDLIST OF RANDOMLY ARRANGED ROOM ENTRIES. THE LIST CONSISTS OF THE ROOM NUMBERS FOR ALL OF THE TOURISTS.
THE ROOM NUMBER WILL APPEEAR K TIMES PER GROUP ECCEPT FOR THE CAPTAIN'S ROOM.
MR. ANANT NEEDS YOU TO HELP HIM FIND THE CAPTAIN'S ROOM NUMBER.
THE TOTAL NUMBER OF TOURISTS OR THE TOTAL NUMBER OF GROUP OF FAMIIES IS NOT KNOWN TO YOU. YOU ONLY KNOWN THE VALUE OFK AND THE ROOM NUMBER LIST.
INPUT FORMAT:
THE FIRST LINE CONSISTS OF AN INTEGER, K, THE SIZE OF EACH GROUP.
THE SECOND LINE CONTAINS THE UNORDERED ELEMENTS OF THE ROOM NUMBER LIST.
CONSTRAINTS:
1<K<1000
OUTPUT FORMAT:
OUTPUT THE CAPTAINS ROOM NUMBER.
SAMPLE INPUT
5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
SAMPLE OUTPUT:
8
EXPLANATION: THE LIST OF ROOM NUMBERS CONTAINS 31 ELEMENTS. SINCE K IS 5, THERE MUST BE 6 GROUPS OF FAMILIES.
IN THE GIVEN LIST, ALL OF THE NUMBERS REPEAT 5 TIMES EXPECT FOR ROOM NUMBER 8.
HENCE, 8 IS THE CAPTAIN'S ROOM NUMBER.
"""

N = int(input())

KEY = map(int, input().split())
KEY = sorted(KEY)

for i in range(len(KEY)):
    if(i != len(KEY)-1):
        if(KEY[i]!=KEY[i-1] and KEY[i]!=KEY[i+1]):
            print(KEY[i])
            break
    else:
        print(KEY[i])